# Generated by Django 5.0 on 2026-02-01 23:11

import django.core.validators
import django.db.models.deletion
import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('node_type', models.CharField(choices=[('warehouse', 'Warehouse'), ('city', 'City Hub'), ('customer', 'Customer Location')], max_length=20)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Latitude coordinate', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Longitude coordinate', max_digits=9)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['node_type'], name='logistics_l_node_ty_83f45c_idx'), models.Index(fields=['is_active'], name='logistics_l_is_acti_40d168_idx')],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('weight_kg', models.FloatField(help_text='Package weight in kilograms', validators=[django.core.validators.MinValueValidator(0.1)])),
                ('description', models.TextField(blank=True)),
                ('state', django_fsm.FSMField(choices=[('pending', 'Pending Pickup'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('current_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages_current', to='logistics.locationnode')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages_destined', to='logistics.locationnode')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages_originating', to='logistics.locationnode')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tracking_id'], name='logistics_p_trackin_d70385_idx'), models.Index(fields=['state'], name='logistics_p_state_ff8b04_idx'), models.Index(fields=['current_location'], name='logistics_p_current_832605_idx')],
            },
        ),
        migrations.CreateModel(
            name='RouteEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.FloatField(help_text='Distance in kilometers', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('travel_time_minutes', models.IntegerField(help_text='Estimated travel time in minutes', validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Road Closed'), ('slow', 'Traffic Delay')], default='active', max_length=20)),
                ('cost_per_km', models.DecimalField(decimal_places=2, default=0.0, help_text='Cost per kilometer for this route', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_routes', to='logistics.locationnode')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_routes', to='logistics.locationnode')),
            ],
            options={
                'ordering': ['source', 'destination'],
                'indexes': [models.Index(fields=['status'], name='logistics_r_status_4a111b_idx'), models.Index(fields=['source', 'destination'], name='logistics_r_source__dc2411_idx')],
                'unique_together': {('source', 'destination')},
            },
        ),
    ]
